### ISSUE TITLE
[bug] duplicated installed_plugin_ref

### ISSUE THREAD

**Issue by choonho** [spaceone-dev/plugin#36]
"plugin-41782f6158bb" : aws-cloud-watch
"domain-a6e9840ed546": spaceone

There may be duplicated installed_plugin_ref, if get_plugin_endpoint asks concurrently.

~~~
2021-04-29T08:03:13.576Z [DEBUG] tnx-fc237bd3dd6b Plugin.get_plugin_endpoint (plugin_ref_manager.py:74) [list] query: ([<InstalledPluginRef: InstalledPluginRef object>, <InstalledPluginRef: InstalledPluginRef object>], 2)
2021-04-29T08:03:13.578Z [ERROR] tnx-fc237bd3dd6b Plugin.get_plugin_endpoint (service.py:144) (Error) => Trying to dereference unknown document DBRef('installed_plugin', ObjectId('6086316864fc7b5c89da305e'))
	error_code = ERROR_UNKNOWN
	status_code = INTERNAL
	message = Trying to dereference unknown document DBRef('installed_plugin', ObjectId('6086316864fc7b5c89da305e'))  Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/spaceone/core/service/service.py", line 105, in _pipeline
    response_or_iterator = func(self, params)
  File "/usr/local/lib/python3.8/site-packages/spaceone/core/service/utils.py", line 41, in wrapped_func
    return func(cls, params)
  File "/usr/local/lib/python3.8/site-packages/spaceone/core/service/utils.py", line 64, in wrapped_func
    return func(cls, params)
  File "/usr/local/lib/python3.8/site-packages/spaceone_plugin-1.6.7-py3.8.egg/spaceone/plugin/service/plugin_service.py", line 50, in get_plugin_endpoint
    _LOGGER.debug(f'[get_plugin_endpoint] selected plugin: {selected_plugin.plugin_owner.endpoint}')
  File "/usr/local/lib/python3.8/site-packages/mongoengine/fields.py", line 1215, in __get__
    raise DoesNotExist("Trying to dereference unknown document %s" % value)
mongoengine.errors.DoesNotExist: Trying to dereference unknown document DBRef('installed_plugin', ObjectId('6086316864fc7b5c89da305e'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/spaceone_plugin-1.6.7-py3.8.egg/spaceone/plugin/api/v1/plugin.py", line 24, in get_plugin_endpoint
    endpoint = plugin_svc.get_plugin_endpoint(params)
  File "/usr/local/lib/python3.8/site-packages/spaceone/core/service/service.py", line 60, in wrapped_func
    return _pipeline(func, self, params, append_meta)
  File "/usr/local/lib/python3.8/site-packages/spaceone/core/service/service.py", line 127, in _pipeline
    raise error
spaceone.core.error.ERROR_UNKNOWN:
	error_code = ERROR_UNKNOWN
	status_code = INTERNAL
	message = Trying to dereference unknown document DBRef('installed_plugin', ObjectId('6086316864fc7b5c89da305e'))
~~~

**Comment by choonho** [comment]
Fix it

**Comment by choonho** [comment]
close
